/*
 *
 * University of Luxembourg
 * Laboratory of Algorithmics, Cryptology and Security (LACS)
 *
 * FELICS - Fair Evaluation of Lightweight Cryptographic Systems
 *
 * Copyright (C) 2015 University of Luxembourg
 *
 * Written in 2015 by Daniel Dinu <dumitru-daniel.dinu@uni.lu>
 *
 * This file is part of FELICS.
 *
 * FELICS is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * FELICS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see <http://www.gnu.org/licenses/>.
 *
 */

#include <stdint.h>

#include "cipher.h"
#include "constants.h"

#ifdef AVR
void Encrypt(uint8_t *block, uint8_t *roundKeys)
{
  /*****************************************************************************/
  /*                                                                           */
  /*ENCRYPT                                                                    */
  /*This routine encrypts a 128 bit plaintext block (supplied in ST11-ST44),   */
  /*using an expanded key given in YH:YL. The resulting 128 bit ciphertext     */
  /*block is stored in ST11-ST44.                                              */
  /*                                                                           */
  /*Parameters:                                                                */
  /*        YH:YL:	pointer to expanded key                                    */
  /*        r0-r15:  128 bit plaintext block                                   */
  /*Touched registers:                                                         */
  /*       r0-r15,r16-r20,r21,ZH,ZL,YH,YL                                      */
  /*Clock cycles:	2474                                                       */
  /*                                                                           */
  /*****************************************************************************/
  asm volatile (\
    /*--------------------------------------------------*/
    /* Store all modified registers                     */
    /*--------------------------------------------------*/
    "push   r0;           \n"
    "push   r1;           \n"
    "push   r2;           \n"
    "push   r3;           \n"
    "push   r4;           \n"
    "push   r5;           \n"
    "push   r6;           \n"
    "push   r7;           \n"
    "push   r8;           \n"
    "push   r9;           \n"
    "push   r10;          \n"
    "push   r11;          \n"
    "push   r12;          \n"
    "push   r13;          \n"
    "push   r14;          \n"
    "push   r15;          \n"
    "push   r16;          \n"
    "push   r17;          \n"
    "push   r18;          \n"
    "push   r19;          \n"
    "push   r20;          \n"
    "push   r21;          \n"
    /*--------------------------------------------------*/
    /* Load plaintext to r0-r15                         */
    /*--------------------------------------------------*/
    "ld r0, x+;           \n"
    "ld r1, x+;           \n"
    "ld r2, x+;           \n"
    "ld r3, x+;           \n"
    "ld r4, x+;           \n"
    "ld r5, x+;           \n"
    "ld r6, x+;           \n"
    "ld r7, x+;           \n"
    "ld r8, x+;           \n"
    "ld r9, x+;           \n"
    "ld r10, x+;          \n"
    "ld r11, x+;          \n"
    "ld r12, x+;          \n"
    "ld r13, x+;          \n"
    "ld r14, x+;          \n"
    "ld r15, x+;          \n"

/*original encryption function*/
    " 	ldi r21, 1 ; 	 \n" /*allow correct return adresses*/
    " rcall encryp1 ; 	 \n"
    " 	ldi ZH, hi8(sbox) ; 	 \n"
    " 	ldi r21, 8 ; 	 \n"
    " encryp0:           \n"
    "   mov ZL, r0		; 1 ; 	 \n"
    " 	lpm r17, Z ; 	 \n"
    " 	mov r18, r17 ; 	 \n"
    " 	mov r19, r17 ; 	 \n"
    " 	ldi ZH, hi8(sbox02) ; 	 \n"
    " 	lpm r16, Z ; 	 \n"
    " 	eor r19, r16 ; 	 \n"
    " 	mov ZL, r5 ; 	 \n"
    " 	lpm r20, Z ; 	 \n"
    " 	eor r16, r20 ; 	 \n"
    " 	eor r17, r20 ; 	 \n"
    " 	ldi ZH, hi8(sbox) ; 	 \n"
    " 	lpm r20, Z ; 	 \n"
    " 	eor r16, r20 ; 	 \n"
    " 	eor r18, r20 ; 	 \n"
    " 	eor r19, r20 ; 	 \n"
    " 	mov ZL, r10 ; 	 \n"
    " 	lpm r20, Z ; 	 \n"
    " 	eor r16, r20 ; 	 \n"
    " 	eor r17, r20 ; 	 \n"
    " 	eor r19, r20 ; 	 \n"
    " 	ldi ZH, hi8(sbox02) ; 	 \n"
    " 	lpm r20, Z ; 	 \n"
    " 	eor r17, r20 ; 	 \n"
    " 	eor r18, r20 ; 	 \n"
    " 	mov ZL, r15 ; 	 \n"
    " 	lpm r20, Z ; 	 \n"
    " 	eor r18, r20 ; 	 \n"
    " 	eor r19, r20 ; 	 \n"
    " 	ldi ZH, hi8(sbox) ; 	 \n"
    " 	lpm r20, Z ; 	 \n"
    " 	eor r16, r20 ; 	 \n"
    " 	eor r17, r20 ; 	 \n"
    " 	eor r18, r20 ; 	 \n"
    " 	ldd r0, Y+0 ; 	 \n"
    " 	eor r0, r16 ; 	 \n"
    " 	mov ZL, r3		; 2 ; 	 \n"
    " 	ldd r3, Y+3 ; 	 \n"
    " 	eor r3, r19 ; 	 \n"
    " 	lpm r16, Z ; 	 \n"
    " 	mov r19, r16 ; 	 \n"
    " 	mov r10, r16 ; 	 \n"
    " 	ldi ZH, hi8(sbox02) ; 	 \n"
    " 	lpm r15, Z ; 	 \n"
    " 	eor r10, r15 ; 	 \n"
    " 	mov ZL, r4 ; 	 \n"
    " 	lpm r20, Z ; 	 \n"
    " 	eor r16, r20 ; 	 \n"
    " 	eor r15, r20 ; 	 \n"
    " 	ldi ZH, hi8(sbox) ; 	 \n"
    " 	lpm r20, Z ; 	 \n"
    " 	eor r19, r20 ; 	 \n"
    " 	eor r10, r20 ; 	 \n"
    " 	eor r15, r20 ; 	 \n"
    " 	mov ZL, r9 ; 	 \n"
    " 	lpm r20, Z ; 	 \n"
    " 	eor r16, r20 ; 	 \n"
    " 	eor r10, r20 ; 	 \n"
    " 	eor r15, r20 ; 	 \n"
    " 	ldi ZH, hi8(sbox02) ; 	 \n"
    " 	lpm r20, Z ; 	 \n"
    " 	eor r16, r20 ; 	 \n"
    " 	eor r19, r20 ; 	 \n"
    " 	mov ZL, r14 ; 	 \n"
    " 	lpm r20, Z ; 	 \n"
    " 	eor r19, r20 ; 	 \n"
    " 	eor r10, r20 ; 	 \n"
    " 	ldi ZH, hi8(sbox) ; 	 \n"
    " 	lpm r20, Z ; 	 \n"
    " 	eor r16, r20 ; 	 \n"
    " 	eor r19, r20 ; 	 \n"
    " 	eor r15, r20 ; 	 \n"
    " 	ldd r4, Y+4 ; 	 \n"
    " 	eor r4, r16 ; 	 \n"
    " 	ldd r5, Y+5 ; 	 \n"
    " 	eor r5, r19 ; 	 \n"
    " 	mov ZL, r2		; 3 ; 	 \n"
    " 	ldd r2, Y+2 ; 	 \n"
    " 	eor r2, r18 ; 	 \n"
    " 	lpm r14, Z ; 	 \n"
    " 	mov r18, r14 ; 	 \n"
    " 	mov r16, r14 ; 	 \n"
    " 	ldi ZH, hi8(sbox02) ; 	 \n"
    " 	lpm r19, Z ; 	 \n"
    " 	eor r18, r19 ; 	 \n"
    " 	mov ZL, r7 ; 	 \n"
    " 	ldd r7, Y+7 ; 	 \n"
    " 	eor r7, r15 ; 	 \n"
    " 	lpm r20, Z ; 	 \n"
    " 	eor r19, r20 ; 	 \n"
    " 	eor r16, r20 ; 	 \n"
    " 	ldi ZH, hi8(sbox) ; 	 \n"
    " 	lpm r20, Z ; 	 \n"
    " 	eor r14, r20 ; 	 \n"
    " 	eor r18, r20 ; 	 \n"
    " 	eor r19, r20 ; 	 \n"
    " 	mov ZL, r8 ; 	 \n"
    " 	lpm r20, Z ; 	 \n"
    " 	eor r18, r20 ; 	 \n"
    " 	eor r19, r20 ; 	 \n"
    " 	eor r16, r20 ; 	 \n"
    " 	ldi ZH, hi8(sbox02) ; 	 \n"
    " 	lpm r20, Z ; 	 \n"
    " 	eor r14, r20 ; 	 \n"
    " 	eor r16, r20 ; 	 \n"
    " 	mov ZL, r13 ; 	 \n"
    " 	lpm r20, Z ; 	 \n"
    " 	eor r14, r20 ; 	 \n"
    " 	eor r18, r20 ; 	 \n"
    " 	ldi ZH, hi8(sbox) ; 	 \n"
    " 	lpm r20, Z ; 	 \n"
    " 	eor r14, r20 ; 	 \n"
    " 	eor r19, r20 ; 	 \n"
    " 	eor r16, r20 ; 	 \n"
    " 	ldd r8, Y+8 ; 	 \n"
    " 	eor r8, r14 ; 	 \n"
    " 	ldd r9, Y+9 ; 	 \n"
    " 	eor r9, r18 ; 	 \n"
    " 	mov ZL, r6		; 4 ; 	 \n"
    " 	ldd r6, Y+6 ; 	 \n"
    " 	eor r6, r10 ; 	 \n"
    " 	ldd r10, Y+10 ; 	 \n"
    " 	eor r10, r19 ; 	 \n"
    " 	lpm r13, Z ; 	 \n"
    " 	mov r14, r13 ; 	 \n"
    " 	mov r19, r13 ; 	 \n"
    " 	ldi ZH, hi8(sbox02) ; 	 \n"
    " 	lpm r18, Z ; 	 \n"
    " 	eor r14, r18 ; 	 \n"
    " 	mov ZL, r11 ; 	 \n"
    " 	ldd r11, Y+11 ; 	 \n"
    " 	eor r11, r16 ; 	 \n"
    " 	lpm r20, Z ; 	 \n"
    " 	eor r18, r20 ; 	 \n"
    " 	eor r19, r20 ; 	 \n"
    " 	ldi ZH, hi8(sbox) ; 	 \n"
    " 	lpm r20, Z ; 	 \n"
    " 	eor r13, r20 ; 	 \n"
    " 	eor r14, r20 ; 	 \n"
    " 	eor r18, r20 ; 	 \n"
    " 	mov ZL, r12 ; 	 \n"
    " 	lpm r20, Z ; 	 \n"
    " 	eor r14, r20 ; 	 \n"
    " 	eor r18, r20 ; 	 \n"
    " 	eor r19, r20 ; 	 \n"
    " 	ldi ZH, hi8(sbox02) ; 	 \n"
    " 	lpm r20, Z ; 	 \n"
    " 	eor r13, r20 ; 	 \n"
    " 	eor r19, r20 ; 	 \n"
    " 	mov ZL, r1 ; 	 \n"
    " 	lpm r20, Z ; 	 \n"
    " 	eor r13, r20 ; 	 \n"
    " 	eor r14, r20 ; 	 \n"
    " 	ldi ZH, hi8(sbox) ; 	 \n"
    " 	lpm r20, Z ; 	 \n"
    " 	eor r13, r20 ; 	 \n"
    " 	eor r18, r20 ; 	 \n"
    " 	eor r19, r20 ; 	 \n"
    " 	ldd r1, Y+1 ; 	 \n"
    " 	eor r1, r17 ; 	 \n"
    " 	ldd r12, Y+12 ; 	 \n"
    " 	eor r12, r13 ; 	 \n"
    " 	ldd r13, Y+13 ; 	 \n"
    " 	eor r13, r14 ; 	 \n"
    " 	ldd r14, Y+14 ; 	 \n"
    " 	eor r14, r18 ; 	 \n"
    " 	ldd r15, Y+15 ; 	 \n"
    " 	eor r15, r19 ; 	 \n"
    /*" 	adiw YH:YL, 16 ; 	 \n" /*GCC errs here*/
    " 	adiw YL, 16 ; 	 \n"
    " 	dec r21 ; 	 \n"
    " 	sbrs r21,7 ; 	 \n"
    " 	jmp encryp0 ; 	 \n"
    " 	mov ZL, r0 ; 	 \n"
    " 	lpm r0, Z ; 	 \n"
    " 	mov ZL, r4 ; 	 \n"
    " 	lpm r4, Z ; 	 \n"
    " 	mov ZL, r8 ; 	 \n"
    " 	lpm r8, Z ; 	 \n"
    " 	mov ZL, r12 ; 	 \n"
    " 	lpm r12, Z ; 	 \n"
    " 	mov r16, r1 ; 	 \n"
    " 	mov ZL, r5 ; 	 \n"
    " 	lpm r1, Z ; 	 \n"
    " 	mov ZL, r9 ; 	 \n"
    " 	lpm r5, Z ; 	 \n"
    " 	mov ZL, r13 ; 	 \n"
    " 	lpm r9, Z ; 	 \n"
    " 	mov ZL, r16 ; 	 \n"
    " 	lpm r13, Z ; 	 \n"
    " 	mov r16, r2 ; 	 \n"
    " 	mov ZL, r10 ; 	 \n"
    " 	lpm r2, Z ; 	 \n"
    " 	mov ZL, r16 ; 	 \n"
    " 	lpm r10, Z ; 	 \n"
    " 	mov r16, r6 ; 	 \n"
    " 	mov ZL, r14 ; 	 \n"
    " 	lpm r6, Z ; 	 \n"
    " 	mov ZL, r16 ; 	 \n"
    " 	lpm r14, Z ; 	 \n"
    " 	mov r16, r3 ; 	 \n"
    " 	mov ZL, r15 ; 	 \n"
    " 	lpm r3, Z ; 	 \n"
    " 	mov ZL, r11 ; 	 \n"
    " 	lpm r15, Z ; 	 \n"
    " 	mov ZL, r7 ; 	 \n"
    " 	lpm r11, Z ; 	 \n"
    " 	mov ZL, r16 ; 	 \n"
    " 	lpm r7, Z ; 	 \n"
    " encryp1:ld r16, Y+ ; 	 \n"
    " 	eor r0, r16 ; 	 \n"
    " 	ld r16, Y+ ; 	 \n"
    " 	eor r1, r16 ; 	 \n"
    " 	ld r16, Y+ ; 	 \n"
    " 	eor r2, r16 ; 	 \n"
    " 	ld r16, Y+ ; 	 \n"
    " 	eor r3, r16 ; 	 \n"
    " 	ld r16, Y+ ; 	 \n"
    " 	eor r4, r16 ; 	 \n"
    " 	ld r16, Y+ ; 	 \n"
    " 	eor r5, r16 ; 	 \n"
    " 	ld r16, Y+ ; 	 \n"
    " 	eor r6, r16 ; 	 \n"
    " 	ld r16, Y+ ; 	 \n"
    " 	eor r7, r16 ; 	 \n"
    " 	ld r16, Y+ ; 	 \n"
    " 	eor r8, r16 ; 	 \n"
    " 	ld r16, Y+ ; 	 \n"
    " 	eor r9, r16 ; 	 \n"
    " 	ld r16, Y+ ; 	 \n"
    " 	eor r10, r16 ; 	 \n"
    " 	ld r16, Y+ ; 	 \n"
    " 	eor r11, r16 ; 	 \n"
    " 	ld r16, Y+ ; 	 \n"
    " 	eor r12, r16 ; 	 \n"
    " 	ld r16, Y+ ; 	 \n"
    " 	eor r13, r16 ; 	 \n"
    " 	ld r16, Y+ ; 	 \n"
    " 	eor r14, r16 ; 	 \n"
    " 	ld r16, Y+ ; 	 \n"
    " 	eor r15, r16 ; 	 \n"
    " 	sbrs r21,7 ; 	 \n" /*jump in the very last execution, when R21=FF (after the counter has run out) */
    "   ret ;            \n"

    /*--------------------------------------------------*/
    /* write ciphertext to memory                       */
    /*--------------------------------------------------*/
    "st    -x,   r15;   \n"
    "st    -x,   r14;   \n"
    "st    -x,   r13;   \n"
    "st    -x,   r12;   \n"
    "st    -x,   r11;   \n"
    "st    -x,   r10;   \n"
    "st    -x,    r9;   \n"
    "st    -x,    r8;   \n"
    "st    -x,    r7;   \n"
    "st    -x,    r6;   \n"
    "st    -x,    r5;   \n"
    "st    -x,    r4;   \n"
    "st    -x,    r3;   \n"
    "st    -x,    r2;   \n"
    "st    -x,    r1;   \n"
    "st    -x,    r0;   \n"
    /*--------------------------------------------------*/
    /* Restore registers                                */
    /*--------------------------------------------------*/
    "pop   r21 ;        \n"
    "pop   r20 ;        \n"
    "pop   r19 ;        \n"
    "pop   r18 ;        \n"
    "pop   r17 ;        \n"
    "pop   r16 ;        \n"
    "pop   r15 ;        \n"
    "pop   r14 ;        \n"
    "pop   r13 ;        \n"
    "pop   r12 ;        \n"
    "pop   r11 ;        \n"
    "pop   r10 ;        \n"
    "pop   r9  ;        \n"
    "pop   r8  ;        \n"
    "pop   r7  ;        \n"
    "pop   r6  ;        \n"
    "pop   r5  ;        \n"
    "pop   r4  ;        \n"
    "pop   r3  ;        \n"
    "pop   r2  ;        \n"
    "pop   r1  ;        \n"
    "pop   r0  ;        \n"
                :
                : [block] "x" (block), [roundKeys] "y" (roundKeys), [sbox] "" (sbox), [sbox02] "" (sbox02)
            );
  }
#endif  /*AVR*/
